services:
  musica-db: 
    image: postgres
    environment: 
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
  app:
    depends_on:
      - musica-db
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
